Test: QG fail check

diff --git a/.github/workflows/pipeline.yaml b/.github/workflows/pipeline.yaml
--- a/.github/workflows/pipeline.yaml
+++ b/.github/workflows/pipeline.yaml
@@ -85,6 +85,12 @@ jobs:
         name: sonarqube-report
         path: reports/sonarqube-report.html
 
+    - name: Fail pipeline at the end if Quality Gate failed
+      if: steps.sonarqube-quality-gate-check.outputs.quality-gate-status == 'FAILED'
+      run: |
+        echo "SonarQube Quality Gate failed"
+        exit 1
+
 
   ####################################################################
 
